// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.alibaba.tailbase.proto;

public interface sendWrongTracingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.sendWrongTracingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string wrongTraceMap = 1;</code>
   */
  java.lang.String getWrongTraceMap();
  /**
   * <code>optional string wrongTraceMap = 1;</code>
   */
  com.google.protobuf.ByteString
      getWrongTraceMapBytes();

  /**
   * <code>optional string batchPos = 2;</code>
   */
  java.lang.String getBatchPos();
  /**
   * <code>optional string batchPos = 2;</code>
   */
  com.google.protobuf.ByteString
      getBatchPosBytes();
}
