// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.alibaba.tailbase.proto;

/**
 * Protobuf type {@code server.sendWrongTracingRequest}
 */
public  final class sendWrongTracingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.sendWrongTracingRequest)
    sendWrongTracingRequestOrBuilder {
  // Use sendWrongTracingRequest.newBuilder() to construct.
  private sendWrongTracingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sendWrongTracingRequest() {
    wrongTraceMap_ = "";
    batchPos_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private sendWrongTracingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            wrongTraceMap_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            batchPos_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.tailbase.proto.ServerProto.internal_static_server_sendWrongTracingRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.tailbase.proto.ServerProto.internal_static_server_sendWrongTracingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.tailbase.proto.sendWrongTracingRequest.class, com.alibaba.tailbase.proto.sendWrongTracingRequest.Builder.class);
  }

  public static final int WRONGTRACEMAP_FIELD_NUMBER = 1;
  private volatile java.lang.Object wrongTraceMap_;
  /**
   * <code>optional string wrongTraceMap = 1;</code>
   */
  public java.lang.String getWrongTraceMap() {
    java.lang.Object ref = wrongTraceMap_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wrongTraceMap_ = s;
      return s;
    }
  }
  /**
   * <code>optional string wrongTraceMap = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWrongTraceMapBytes() {
    java.lang.Object ref = wrongTraceMap_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wrongTraceMap_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCHPOS_FIELD_NUMBER = 2;
  private volatile java.lang.Object batchPos_;
  /**
   * <code>optional string batchPos = 2;</code>
   */
  public java.lang.String getBatchPos() {
    java.lang.Object ref = batchPos_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchPos_ = s;
      return s;
    }
  }
  /**
   * <code>optional string batchPos = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBatchPosBytes() {
    java.lang.Object ref = batchPos_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchPos_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWrongTraceMapBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wrongTraceMap_);
    }
    if (!getBatchPosBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, batchPos_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWrongTraceMapBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wrongTraceMap_);
    }
    if (!getBatchPosBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, batchPos_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.tailbase.proto.sendWrongTracingRequest)) {
      return super.equals(obj);
    }
    com.alibaba.tailbase.proto.sendWrongTracingRequest other = (com.alibaba.tailbase.proto.sendWrongTracingRequest) obj;

    boolean result = true;
    result = result && getWrongTraceMap()
        .equals(other.getWrongTraceMap());
    result = result && getBatchPos()
        .equals(other.getBatchPos());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + WRONGTRACEMAP_FIELD_NUMBER;
    hash = (53 * hash) + getWrongTraceMap().hashCode();
    hash = (37 * hash) + BATCHPOS_FIELD_NUMBER;
    hash = (53 * hash) + getBatchPos().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.tailbase.proto.sendWrongTracingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.tailbase.proto.sendWrongTracingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code server.sendWrongTracingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.sendWrongTracingRequest)
      com.alibaba.tailbase.proto.sendWrongTracingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.tailbase.proto.ServerProto.internal_static_server_sendWrongTracingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.tailbase.proto.ServerProto.internal_static_server_sendWrongTracingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.tailbase.proto.sendWrongTracingRequest.class, com.alibaba.tailbase.proto.sendWrongTracingRequest.Builder.class);
    }

    // Construct using com.alibaba.tailbase.proto.sendWrongTracingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      wrongTraceMap_ = "";

      batchPos_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.tailbase.proto.ServerProto.internal_static_server_sendWrongTracingRequest_descriptor;
    }

    public com.alibaba.tailbase.proto.sendWrongTracingRequest getDefaultInstanceForType() {
      return com.alibaba.tailbase.proto.sendWrongTracingRequest.getDefaultInstance();
    }

    public com.alibaba.tailbase.proto.sendWrongTracingRequest build() {
      com.alibaba.tailbase.proto.sendWrongTracingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.alibaba.tailbase.proto.sendWrongTracingRequest buildPartial() {
      com.alibaba.tailbase.proto.sendWrongTracingRequest result = new com.alibaba.tailbase.proto.sendWrongTracingRequest(this);
      result.wrongTraceMap_ = wrongTraceMap_;
      result.batchPos_ = batchPos_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.tailbase.proto.sendWrongTracingRequest) {
        return mergeFrom((com.alibaba.tailbase.proto.sendWrongTracingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.tailbase.proto.sendWrongTracingRequest other) {
      if (other == com.alibaba.tailbase.proto.sendWrongTracingRequest.getDefaultInstance()) return this;
      if (!other.getWrongTraceMap().isEmpty()) {
        wrongTraceMap_ = other.wrongTraceMap_;
        onChanged();
      }
      if (!other.getBatchPos().isEmpty()) {
        batchPos_ = other.batchPos_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.tailbase.proto.sendWrongTracingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.tailbase.proto.sendWrongTracingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object wrongTraceMap_ = "";
    /**
     * <code>optional string wrongTraceMap = 1;</code>
     */
    public java.lang.String getWrongTraceMap() {
      java.lang.Object ref = wrongTraceMap_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wrongTraceMap_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string wrongTraceMap = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWrongTraceMapBytes() {
      java.lang.Object ref = wrongTraceMap_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wrongTraceMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string wrongTraceMap = 1;</code>
     */
    public Builder setWrongTraceMap(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wrongTraceMap_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string wrongTraceMap = 1;</code>
     */
    public Builder clearWrongTraceMap() {
      
      wrongTraceMap_ = getDefaultInstance().getWrongTraceMap();
      onChanged();
      return this;
    }
    /**
     * <code>optional string wrongTraceMap = 1;</code>
     */
    public Builder setWrongTraceMapBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wrongTraceMap_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object batchPos_ = "";
    /**
     * <code>optional string batchPos = 2;</code>
     */
    public java.lang.String getBatchPos() {
      java.lang.Object ref = batchPos_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchPos_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string batchPos = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBatchPosBytes() {
      java.lang.Object ref = batchPos_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchPos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string batchPos = 2;</code>
     */
    public Builder setBatchPos(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batchPos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string batchPos = 2;</code>
     */
    public Builder clearBatchPos() {
      
      batchPos_ = getDefaultInstance().getBatchPos();
      onChanged();
      return this;
    }
    /**
     * <code>optional string batchPos = 2;</code>
     */
    public Builder setBatchPosBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batchPos_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:server.sendWrongTracingRequest)
  }

  // @@protoc_insertion_point(class_scope:server.sendWrongTracingRequest)
  private static final com.alibaba.tailbase.proto.sendWrongTracingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.tailbase.proto.sendWrongTracingRequest();
  }

  public static com.alibaba.tailbase.proto.sendWrongTracingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sendWrongTracingRequest>
      PARSER = new com.google.protobuf.AbstractParser<sendWrongTracingRequest>() {
    public sendWrongTracingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new sendWrongTracingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sendWrongTracingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<sendWrongTracingRequest> getParserForType() {
    return PARSER;
  }

  public com.alibaba.tailbase.proto.sendWrongTracingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

