// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.alibaba.tailbase.proto;

public interface setWrongTraceIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.setWrongTraceIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string traceIdListJson = 1;</code>
   */
  String getTraceIdListJson();
  /**
   * <code>optional string traceIdListJson = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdListJsonBytes();

  /**
   * <code>optional int32 batchPos = 2;</code>
   */
  int getBatchPos();
}
