// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.alibaba.tailbase.proto;

public interface setWrongTraceIdReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.setWrongTraceIdReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
