// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

package com.alibaba.tailbase.proto;

/**
 * Protobuf type {@code server.setWrongTraceIdRequest}
 */
public  final class setWrongTraceIdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.setWrongTraceIdRequest)
    setWrongTraceIdRequestOrBuilder {
  // Use setWrongTraceIdRequest.newBuilder() to construct.
  private setWrongTraceIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private setWrongTraceIdRequest() {
    traceIdListJson_ = "";
    batchPos_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private setWrongTraceIdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            traceIdListJson_ = s;
            break;
          }
          case 16: {

            batchPos_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ServerProto.internal_static_server_setWrongTraceIdRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ServerProto.internal_static_server_setWrongTraceIdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            setWrongTraceIdRequest.class, setWrongTraceIdRequest.Builder.class);
  }

  public static final int TRACEIDLISTJSON_FIELD_NUMBER = 1;
  private volatile Object traceIdListJson_;
  /**
   * <code>optional string traceIdListJson = 1;</code>
   */
  public String getTraceIdListJson() {
    Object ref = traceIdListJson_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      traceIdListJson_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceIdListJson = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTraceIdListJsonBytes() {
    Object ref = traceIdListJson_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      traceIdListJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCHPOS_FIELD_NUMBER = 2;
  private int batchPos_;
  /**
   * <code>optional int32 batchPos = 2;</code>
   */
  public int getBatchPos() {
    return batchPos_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTraceIdListJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, traceIdListJson_);
    }
    if (batchPos_ != 0) {
      output.writeInt32(2, batchPos_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTraceIdListJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, traceIdListJson_);
    }
    if (batchPos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, batchPos_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof setWrongTraceIdRequest)) {
      return super.equals(obj);
    }
    setWrongTraceIdRequest other = (setWrongTraceIdRequest) obj;

    boolean result = true;
    result = result && getTraceIdListJson()
        .equals(other.getTraceIdListJson());
    result = result && (getBatchPos()
        == other.getBatchPos());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TRACEIDLISTJSON_FIELD_NUMBER;
    hash = (53 * hash) + getTraceIdListJson().hashCode();
    hash = (37 * hash) + BATCHPOS_FIELD_NUMBER;
    hash = (53 * hash) + getBatchPos();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static setWrongTraceIdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static setWrongTraceIdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static setWrongTraceIdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static setWrongTraceIdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static setWrongTraceIdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static setWrongTraceIdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static setWrongTraceIdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static setWrongTraceIdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static setWrongTraceIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static setWrongTraceIdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(setWrongTraceIdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code server.setWrongTraceIdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.setWrongTraceIdRequest)
      setWrongTraceIdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerProto.internal_static_server_setWrongTraceIdRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerProto.internal_static_server_setWrongTraceIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              setWrongTraceIdRequest.class, setWrongTraceIdRequest.Builder.class);
    }

    // Construct using com.alibaba.tailbase.proto.setWrongTraceIdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      traceIdListJson_ = "";

      batchPos_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ServerProto.internal_static_server_setWrongTraceIdRequest_descriptor;
    }

    public setWrongTraceIdRequest getDefaultInstanceForType() {
      return setWrongTraceIdRequest.getDefaultInstance();
    }

    public setWrongTraceIdRequest build() {
      setWrongTraceIdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public setWrongTraceIdRequest buildPartial() {
      setWrongTraceIdRequest result = new setWrongTraceIdRequest(this);
      result.traceIdListJson_ = traceIdListJson_;
      result.batchPos_ = batchPos_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof setWrongTraceIdRequest) {
        return mergeFrom((setWrongTraceIdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(setWrongTraceIdRequest other) {
      if (other == setWrongTraceIdRequest.getDefaultInstance()) return this;
      if (!other.getTraceIdListJson().isEmpty()) {
        traceIdListJson_ = other.traceIdListJson_;
        onChanged();
      }
      if (other.getBatchPos() != 0) {
        setBatchPos(other.getBatchPos());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      setWrongTraceIdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (setWrongTraceIdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object traceIdListJson_ = "";
    /**
     * <code>optional string traceIdListJson = 1;</code>
     */
    public String getTraceIdListJson() {
      Object ref = traceIdListJson_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        traceIdListJson_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string traceIdListJson = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdListJsonBytes() {
      Object ref = traceIdListJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        traceIdListJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceIdListJson = 1;</code>
     */
    public Builder setTraceIdListJson(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      traceIdListJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceIdListJson = 1;</code>
     */
    public Builder clearTraceIdListJson() {

      traceIdListJson_ = getDefaultInstance().getTraceIdListJson();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceIdListJson = 1;</code>
     */
    public Builder setTraceIdListJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      traceIdListJson_ = value;
      onChanged();
      return this;
    }

    private int batchPos_ ;
    /**
     * <code>optional int32 batchPos = 2;</code>
     */
    public int getBatchPos() {
      return batchPos_;
    }
    /**
     * <code>optional int32 batchPos = 2;</code>
     */
    public Builder setBatchPos(int value) {

      batchPos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batchPos = 2;</code>
     */
    public Builder clearBatchPos() {

      batchPos_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:server.setWrongTraceIdRequest)
  }

  // @@protoc_insertion_point(class_scope:server.setWrongTraceIdRequest)
  private static final setWrongTraceIdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new setWrongTraceIdRequest();
  }

  public static setWrongTraceIdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<setWrongTraceIdRequest>
      PARSER = new com.google.protobuf.AbstractParser<setWrongTraceIdRequest>() {
    public setWrongTraceIdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new setWrongTraceIdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<setWrongTraceIdRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<setWrongTraceIdRequest> getParserForType() {
    return PARSER;
  }

  public setWrongTraceIdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

